name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Build project
      run: npm run build
      env:
        CI: false
        
    - name: Copy SEO files to build directory
      run: |
        # Ensure robots.txt and sitemap.xml are in the build folder
        cp public/robots.txt build/robots.txt || true
        cp public/sitemap.xml build/sitemap.xml || true
        cp public/404.html build/404.html || true
        # Copy CNAME if it exists
        [ -f CNAME ] && cp CNAME build/CNAME || true
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        # Keep existing files that might be in gh-pages branch
        keep_files: false
        # Custom commit message
        commit_message: 'Deploy with SEO optimizations' 